apiVersion: apps/v1
kind: Deployment
metadata:
  name: speech-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speech
  template:
    metadata:
      labels:
        app: speech
    spec:
      containers:
        - name: speech
          image: niloyrudra/speech-service
          imagePullPolicy: IfNotPresent
          env:
            - name: NLP_SERVICE_URL
              value: http://nlp-srv:8000
          ports:
            - containerPort: 8001

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"

          readinessProbe:
            httpGet:
              path: /docs
              port: 8001
            initialDelaySeconds: 60 # model may take time to load
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /docs
              port: 8001
            initialDelaySeconds: 120
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: speech-srv
spec:
  selector:
    app: speech
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
