apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: niloyrudra/auth
      context: services/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: niloyrudra/achievements
      context: services/achievements
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: niloyrudra/streaks
      context: services/streaks
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: niloyrudra/progress
      context: services/progress
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: niloyrudra/performance
      context: services/performance
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: niloyrudra/profile
      context: services/profile
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: niloyrudra/settings
      context: services/settings
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
            
    - image: niloyrudra/category
      context: services/category
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: niloyrudra/unit
      context: services/unit
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: niloyrudra/practice
      context: services/practice
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: niloyrudra/quiz
      context: services/quiz
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: niloyrudra/speaking
      context: services/speaking
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: niloyrudra/reading
      context: services/reading
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: niloyrudra/listening
      context: services/listening
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: niloyrudra/writing
      context: services/writing
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
            
    - image: niloyrudra/nlp-service
      context: services/nlp-service
      docker:
        dockerfile: Dockerfile

profiles:
  - name: db
    deploy:
      kubectl:
        manifests:
          - infra/k8s/auth/auth-postgres-pvc.yaml
          - infra/k8s/auth/auth-postgres-depl.yaml
          - infra/k8s/streaks/streaks-postgres-pvc.yaml
          - infra/k8s/streaks/streaks-postgres-depl.yaml
          - infra/k8s/progress/progress-postgres-pvc.yaml
          - infra/k8s/progress/progress-postgres-depl.yaml
          - infra/k8s/performance/performance-postgres-pvc.yaml
          - infra/k8s/performance/performance-postgres-depl.yaml
          - infra/k8s/profile/profile-postgres-pvc.yaml
          - infra/k8s/profile/profile-postgres-depl.yaml
          - infra/k8s/settings/settings-postgres-pvc.yaml
          - infra/k8s/settings/settings-postgres-depl.yaml
          - infra/k8s/achievements/achievements-postgres-pvc.yaml
          - infra/k8s/achievements/achievements-postgres-depl.yaml
          - infra/k8s/auth/auth-secrets.yaml
          - infra/k8s/streaks/streaks-postgres-secrets.yaml
          - infra/k8s/progress/progress-secrets.yaml
          - infra/k8s/performance/performance-secrets.yaml
          - infra/k8s/mongo-secrets.yaml
          - infra/k8s/category/category-mongo-secrets.yaml
          - infra/k8s/unit/unit-mongo-secrets.yaml
          - infra/k8s/practice/practice-mongo-secrets.yaml
          - infra/k8s/quiz/quiz-mongo-secrets.yaml
          - infra/k8s/reading/reading-mongo-secrets.yaml
          - infra/k8s/listening/listening-mongo-secrets.yaml
          - infra/k8s/speaking/speaking-mongo-secrets.yaml
          - infra/k8s/writing/writing-mongo-secrets.yaml

  - name: apps
    deploy:
      kubectl:
        manifests:
          - infra/k8s/auth/auth-depl.yaml
          - infra/k8s/profile/profile-depl.yaml
          - infra/k8s/settings/settings-depl.yaml
          - infra/k8s/achievements/achievements-depl.yaml
          - infra/k8s/streaks/streaks-depl.yaml
          - infra/k8s/progress/progress-depl.yaml
          - infra/k8s/performance/performance-depl.yaml
          - infra/k8s/category/category-depl.yaml
          - infra/k8s/unit/unit-depl.yaml
          - infra/k8s/practice/practice-depl.yaml
          - infra/k8s/quiz/quiz-depl.yaml
          - infra/k8s/speaking/speaking-depl.yaml
          - infra/k8s/reading/reading-depl.yaml
          - infra/k8s/listening/listening-depl.yaml
          - infra/k8s/writing/writing-depl.yaml
          - infra/k8s/nlp/nlp-depl.yaml
          - infra/k8s/speech/speech-depl.yaml
          - infra/k8s/kafka/kafka-depl.yaml
          - infra/k8s/kafka/zookeeper-depl.yaml
          - infra/k8s/ingress/ingress-srv.yaml
