apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-postgres
  template:
    metadata:
      labels:
        app: notification-postgres
    spec:
      containers:
        - name: notification-postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: POSTGRES_PASSWORD
                  
          volumeMounts:
            - name: notification-postgres-srv # postgres-data
              mountPath: /var/lib/postgresql/data
      # volumes:
      #   - name: postgres-data
      #     emptyDir: {}
      volumes:
        - name: notification-postgres-srv
          persistentVolumeClaim:
            claimName: notification-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: notification-postgres-srv
spec:
  selector:
    app: notification-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432