apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaks-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaks
  template:
    metadata:
      labels:
        app: streaks
    spec:
      initContainers:
        - name: db-migrate
          image: niloyrudra/streaks
          command: [ "node", "dist/db/migrate.js" ]
          envFrom:
            - secretRef:
                name: streaks-postgres-secrets

      containers:
        - name: streaks
          image: niloyrudra/streaks
          env:
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: streaks-postgres-secrets
                  key: PG_HOST

            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: streaks-postgres-secrets
                  key: PG_PORT

            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: streaks-postgres-secrets
                  key: PG_USER

            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: streaks-postgres-secrets
                  key: PG_PASSWORD

            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: streaks-postgres-secrets
                  key: PG_DB

            - name: SERVICE_NAME
              value: streaks-service

            - name: KAFKA_BROKER
              value: kafka-srv:9092
            
          ports:
            - containerPort: 3001

          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

          readinessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20

          # Liveness probe → checks if container is alive
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3001
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
          #   timeoutSeconds: 3
          #   failureThreshold: 3

          # # Readiness probe → checks if container is ready to receive traffic
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 3001
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 2
          #   failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: streaks-srv
spec:
  selector:
    app: streaks
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  # type: ClusterIP
