apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      initContainers:
        - name: db-migrate
          image: niloyrudra/profile
          command: [ "node", "dist/db/migrate.js" ]
          envFrom:
            - secretRef:
                name: profile-secrets

      containers:
        - name: profile
          image: niloyrudra/profile
          env:
            - name: SERVICE_NAME
              value: profile-service

            - name: KAFKA_BROKER
              value: kafka-srv:9092

            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: profile-secrets
                  key: PG_HOST

            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: profile-secrets
                  key: PG_PORT

            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: profile-secrets
                  key: PG_USER

            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profile-secrets
                  key: PG_PASSWORD
                  
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: profile-secrets
                  key: PG_DB

            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: profile-secrets
                  key: JWT_KEY

          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          # Ensuring pods restart if Kafka is down
          readinessProbe:
            tcpSocket:
              port: 3004
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 3004
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: profile-srv
spec:
  selector:
    app: profile
  ports:
    - name: profile
      protocol: TCP
      port: 3004
      targetPort: 3004


