apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress-postgres
  template:
    metadata:
      labels:
        app: progress-postgres
    spec:
      containers:
      - name: progress-postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: progress-postgres-secrets
                key: DATABASE_URL
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: progress-postgres-secrets
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: progress-postgres-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: progress-postgres-secrets
                key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: progress-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: progress-postgres-srv
spec:
  selector:
    app: progress-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432