apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress
  template:
    metadata:
      labels:
        app: progress
    spec:
      # <<< ADD INIT CONTAINER HERE
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z $DB_HOST $DB_PORT; do echo waiting for db; sleep 2; done;']
          env:
            - name: DB_HOST
              value: progress-postgres-srv
            - name: DB_PORT
              value: "5432"
          imagePullPolicy: IfNotPresent

      containers:
        - name: progress
          image: niloyrudra/progress-service
          ports:
            - containerPort: 3002
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: progress-postgres-secrets
                  key: DATABASE_URL
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: progress-postgres-secrets
                  key: POSTGRES_DB

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: progress-postgres-secrets
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: progress-postgres-secrets
                  key: POSTGRES_PASSWORD

            - name: DB_HOST
              value: progress-postgres-srv

            - name: DB_PORT
              value: "5432"

            - name: KAFKA_BROKER
              value: kafka-srv:9092

          # livenessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 3002
          #   initialDelaySeconds: 15
          #   periodSeconds: 10

          # readinessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 3002
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
            
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: progress-srv
spec:
  selector:
    app: progress
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  # type: ClusterIP