apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress
  template:
    metadata:
      labels:
        app: progress
    spec:
      initContainers:
        - name: db-migrate
          image: niloyrudra/progress
          command: [ "node", "dist/db/migrate.js" ]
          envFrom:
            - secretRef:
                name: progress-secrets

      containers:
        - name: progress
          image: niloyrudra/progress
          env:
            - name: SERVICE_NAME
              value: progress-service

            - name: KAFKA_BROKER
              value: kafka-srv:9092
            
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: progress-secrets
                  key: PG_HOST

            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: progress-secrets
                  key: PG_PORT

            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: progress-secrets
                  key: PG_USER

            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: progress-secrets
                  key: PG_PASSWORD
                  
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: progress-secrets
                  key: PG_DB

          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

          readinessProbe:
            tcpSocket:
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: progress-srv
spec:
  selector:
    app: progress
  ports:
    - name: progress
      protocol: TCP
      port: 3002
      targetPort: 3002


