apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-model-cache-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce #ReadWriteMany
