apiVersion: apps/v1
kind: Deployment
metadata:
  name: settings-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settings
  template:
    metadata:
      labels:
        app: settings
    spec:
      containers:
        - name: settings
          image: niloyrudra/settings
          env:
            - name: SERVICE_NAME
              value: settings-service

            - name: KAFKA_BROKER
              value: kafka-srv:9092

            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: settings-secrets
                  key: PG_HOST
                  
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: settings-secrets
                  key: PG_PORT

            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: settings-secrets
                  key: PG_USER

            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: settings-secrets
                  key: PG_PASSWORD

            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: settings-secrets
                  key: PG_DB
                  
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          # Ensuring pods restart if Kafka is down
          readinessProbe:
            tcpSocket:
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 3005
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: settings-srv
spec:
  selector:
    app: settings
  ports:
    - name: settings
      protocol: TCP
      port: 3005
      targetPort: 3005


